$ErrorActionPreference = "Stop"
if (-not $env:BCC_DATA_DIR) {
  Write-Host "OWNER_ACTION_REQUIRED: set BCC_DATA_DIR to your configured Bossman data directory." -ForegroundColor Yellow
  exit 2
}
$out = Join-Path (Get-Location) "OWNER_HARDWARE_CERTIFICATION.json"
python -I -m bcc.owner_acceptance --data-dir "$env:BCC_DATA_DIR" --output "$out"
$code = $LASTEXITCODE
if (Test-Path $out) {
  $data = Get-Content $out -Raw | ConvertFrom-Json
  $md = @(
    "# OWNER HARDWARE CERTIFICATION",
    "",
    "Generated by the installed Bossman owner-acceptance harness.",
    "",
    "- Overall: $($data.status)",
    "- BOOT: $($data.BOOT)",
    "- CORE_LIVE_API: $($data.CORE_LIVE_API)",
    "- REAL_AGENT_TASK: $($data.REAL_AGENT_TASK)",
    "- RESTART_PERSISTENCE: $($data.RESTART_PERSISTENCE)",
    "- CORE_UI: $($data.CORE_UI)",
    "",
    "Continue with HW-01..HW-12 from tests/owner_hardware/manifest.json.",
    "Real Telegram/local-model/desktop/account steps remain OWNER_ACTION_REQUIRED until performed."
  )
  $md | Set-Content -Encoding UTF8 "OWNER_HARDWARE_CERTIFICATION.md"
  Write-Host "Wrote OWNER_HARDWARE_CERTIFICATION.md"
}
exit $code
