$ErrorActionPreference = "Stop"

$root = $PSScriptRoot
$out = Join-Path $root "OWNER_HARDWARE_CERTIFICATION.json"
$mdOut = Join-Path $root "OWNER_HARDWARE_CERTIFICATION.md"

# Invalidate earlier success BEFORE configuration/runtime checks can exit.
if (Test-Path $out) { Remove-Item -Force $out }
if (Test-Path $mdOut) { Remove-Item -Force $mdOut }

if (-not $env:BCC_DATA_DIR) {
  Write-Host "OWNER_ACTION_REQUIRED: set BCC_DATA_DIR to your configured Bossman data directory." -ForegroundColor Yellow
  exit 2
}

$manifestPath = Join-Path $root "MANIFEST.json"
$installedBundle = (Test-Path $manifestPath) -or (Test-Path (Join-Path $root "app-support"))
$manifest = $null
if ($installedBundle) {
  try {
    $manifest = Get-Content -LiteralPath $manifestPath -Raw -Encoding UTF8 | ConvertFrom-Json
    if ($manifest.source_sha -cnotmatch '^[0-9a-f]{40}$' -or $manifest.source_dirty -ne $false) {
      throw "invalid build identity"
    }
  } catch {
    Write-Host "FAIL: installed bundle has no valid clean build identity." -ForegroundColor Red
    exit 1
  }
}

# A damaged installed product must never run a different system installation.
# The checkout-only fallback remains explicitly labelled as engineering evidence.
$bundledPython = Join-Path $root "runtime\python.exe"
if (Test-Path $bundledPython) {
  $python = $bundledPython
} else {
  if ($installedBundle) {
    Write-Host "FAIL: installed bundle runtime is missing; no system Python fallback is allowed." -ForegroundColor Red
    exit 1
  }
  $systemPython = Get-Command python -ErrorAction SilentlyContinue
  if (-not $systemPython) {
    Write-Host "FAIL: no bundled runtime\python.exe and no system python for checkout fallback." -ForegroundColor Red
    exit 1
  }
  $python = $systemPython.Source
  Write-Host "ENGINEERING_ONLY: bundled runtime not found; using system Python. This is not installed-product evidence." -ForegroundColor Yellow
}

& $python -I -m bcc.owner_acceptance --data-dir "$env:BCC_DATA_DIR" --output "$out"
$code = $LASTEXITCODE

if (-not (Test-Path $out)) {
  Write-Host "FAIL: current owner-acceptance run produced no JSON result; no previous result is accepted." -ForegroundColor Red
  if ($code -eq 0) { $code = 1 }
  exit $code
}

try {
  $data = Get-Content $out -Raw -Encoding UTF8 | ConvertFrom-Json
} catch {
  Write-Host "FAIL: current owner-acceptance JSON is unreadable." -ForegroundColor Red
  exit 1
}

# Preserve genuine failures/OWNER_REQUIRED, but never publish a contradictory PASS.
if (($data.status -notin @('PASS', 'FAIL', 'OWNER_REQUIRED')) -or
    (($data.status -eq 'PASS') -and ($code -ne 0)) -or
    (($data.status -ne 'PASS') -and ($code -eq 0))) {
  Remove-Item -Force $out
  Write-Host "FAIL: owner-acceptance receipt contradicts its process exit code." -ForegroundColor Red
  exit 1
}
if ($installedBundle -and $data.status -eq 'PASS' -and
    ($data.source_sha -cne $manifest.source_sha -or $data.source_dirty -ne $false)) {
  Remove-Item -Force $out
  Write-Host "FAIL: owner-acceptance receipt does not match this bundle." -ForegroundColor Red
  exit 1
}

$md = @(
  "# OWNER CORE ACCEPTANCE",
  "",
  "Generated by the current Bossman owner-acceptance harness.",
  "Hardware certification: NOT_PERFORMED. The legacy output filename is retained for compatibility.",
  "",
  "- Overall: $($data.status)",
  "- Process exit code: $code",
  "- Source SHA: $($data.source_sha)",
  "- Scope: $($data.scope)",
  "- BOOT: $($data.BOOT)",
  "- CORE_LIVE_API: $($data.CORE_LIVE_API)",
  "- REAL_AGENT_TASK: $($data.REAL_AGENT_TASK)",
  "- RESTART_PERSISTENCE: $($data.RESTART_PERSISTENCE)",
  "- CORE_UI: $($data.CORE_UI)",
  "",
  "Continue with HW-01..HW-13 from tests/owner_hardware/manifest.json.",
  "Real Telegram/local-model/desktop/account/MVCR steps remain OWNER_ACTION_REQUIRED until performed."
)
$md | Set-Content -Encoding UTF8 $mdOut
Write-Host "Wrote $mdOut"

exit $code
