$ErrorActionPreference = "Stop"

if (-not $env:BCC_DATA_DIR) {
  Write-Host "OWNER_ACTION_REQUIRED: set BCC_DATA_DIR to your configured Bossman data directory." -ForegroundColor Yellow
  exit 2
}

$root = $PSScriptRoot
$out = Join-Path $root "OWNER_HARDWARE_CERTIFICATION.json"
$mdOut = Join-Path $root "OWNER_HARDWARE_CERTIFICATION.md"

# Never allow an earlier successful run to satisfy a failed current run.
if (Test-Path $out) { Remove-Item -Force $out }
if (Test-Path $mdOut) { Remove-Item -Force $mdOut }

# Installed candidates must use their own runtime. A checkout can still use a
# system Python for engineering/debugging, but that is not installed-product evidence.
$bundledPython = Join-Path $root "runtime\python.exe"
if (Test-Path $bundledPython) {
  $python = $bundledPython
} else {
  $systemPython = Get-Command python -ErrorAction SilentlyContinue
  if (-not $systemPython) {
    Write-Host "FAIL: no bundled runtime\python.exe and no system python for checkout fallback." -ForegroundColor Red
    exit 1
  }
  $python = $systemPython.Source
  Write-Host "ENGINEERING_ONLY: bundled runtime not found; using system Python. This is not installed-product evidence." -ForegroundColor Yellow
}

& $python -I -m bcc.owner_acceptance --data-dir "$env:BCC_DATA_DIR" --output "$out"
$code = $LASTEXITCODE

if (-not (Test-Path $out)) {
  Write-Host "FAIL: current owner-acceptance run produced no JSON result; no previous result is accepted." -ForegroundColor Red
  if ($code -eq 0) { $code = 1 }
  exit $code
}

try {
  $data = Get-Content $out -Raw | ConvertFrom-Json
} catch {
  Write-Host "FAIL: current owner-acceptance JSON is unreadable: $($_.Exception.Message)" -ForegroundColor Red
  exit 1
}

$md = @(
  "# OWNER HARDWARE CERTIFICATION",
  "",
  "Generated by the current Bossman owner-acceptance harness.",
  "",
  "- Overall: $($data.status)",
  "- BOOT: $($data.BOOT)",
  "- CORE_LIVE_API: $($data.CORE_LIVE_API)",
  "- REAL_AGENT_TASK: $($data.REAL_AGENT_TASK)",
  "- RESTART_PERSISTENCE: $($data.RESTART_PERSISTENCE)",
  "- CORE_UI: $($data.CORE_UI)",
  "",
  "Continue with HW-01..HW-13 from tests/owner_hardware/manifest.json.",
  "Real Telegram/local-model/desktop/account/MVCR steps remain OWNER_ACTION_REQUIRED until performed."
)
$md | Set-Content -Encoding UTF8 $mdOut
Write-Host "Wrote $mdOut"

exit $code
