"""Release evidence observes bytes even when Git's ordinary view hides them."""
import importlib.util
import json
import os
from pathlib import Path
import subprocess
import sys

import pytest


ROOT = Path(__file__).resolve().parents[1]


def module(name):
    spec = importlib.util.spec_from_file_location(name, ROOT / "tools" / f"{name}.py")
    value = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(value)
    return value


identity = module("build_source_identity")
builder = module("build_local_bundle")
verifier = module("verify_installed_product")


def git(root, *args):
    return subprocess.check_output(["git", "-C", str(root), *args], stderr=subprocess.PIPE).decode().strip()


@pytest.fixture
def repository(tmp_path):
    git(tmp_path, "init")
    (tmp_path / "bossman_shared").mkdir()
    (tmp_path / "bossman_shared/runtime.py").write_text("VALUE = 1\n")
    (tmp_path / ".gitignore").write_text("build/\n__pycache__/\n")
    git(tmp_path, "add", ".")
    git(tmp_path, "-c", "user.name=Build regression", "-c", "user.email=build@example.invalid",
        "commit", "-m", "fixture source")
    return tmp_path


def test_clean_source_has_strict_false_identity(repository):
    assert identity.source_identity(repository) == {
        "source_sha": git(repository, "rev-parse", "HEAD"), "source_dirty": False}


@pytest.mark.parametrize("flag", ["--assume-unchanged", "--skip-worktree"])
def test_hidden_same_size_restored_mtime_edit_is_dirty(repository, flag):
    path = repository / "bossman_shared/runtime.py"
    stamp = path.stat()
    git(repository, "update-index", flag, "bossman_shared/runtime.py")
    path.write_text("VALUE = 2\n")
    os.utime(path, ns=(stamp.st_atime_ns, stamp.st_mtime_ns))
    assert git(repository, "status", "--porcelain") == ""
    assert identity.source_identity(repository)["source_dirty"] is True


def test_ignored_untracked_source_is_dirty(repository):
    (repository / ".git/info/exclude").write_text("bossman_shared/hidden.py\n")
    (repository / "bossman_shared/hidden.py").write_text("MUTATION = True\n")
    assert git(repository, "status", "--porcelain") == ""
    assert identity.source_identity(repository)["source_dirty"] is True


def test_generated_bytecode_does_not_change_source_identity(repository):
    cache = repository / "bossman_shared/__pycache__"
    cache.mkdir()
    (cache / "runtime.cpython-312.pyc").write_bytes(b"generated bytecode")
    assert identity.source_identity(repository)["source_dirty"] is False


def test_fresh_snapshot_excludes_hidden_edits_and_stale_build_output(repository, monkeypatch):
    sha = git(repository, "rev-parse", "HEAD")
    git(repository, "update-index", "--skip-worktree", "bossman_shared/runtime.py")
    (repository / "bossman_shared/runtime.py").write_text("VALUE = 2\n")
    stale = repository / "build/lib/bossman_shared/injected.py"
    stale.parent.mkdir(parents=True)
    stale.write_text("unreviewed = True\n")
    monkeypatch.setattr(builder, "ROOT", repository)
    with builder.clean_source_snapshot(sha) as snapshot:
        assert (snapshot / "bossman_shared/runtime.py").read_text() == "VALUE = 1\n"
        assert not (snapshot / "build").exists()
        assert identity.source_identity(snapshot) == {"source_sha": sha, "source_dirty": False}
    assert not snapshot.exists()
    assert (repository / "bossman_shared/runtime.py").read_text() == "VALUE = 2\n"


def test_snapshot_is_byte_faithful_with_autocrlf_without_normalizing_binary(repository, monkeypatch):
    binary = b"\0binary\r\nbytes\r\n"
    (repository / "asset.bin").write_bytes(binary)
    git(repository, "add", "asset.bin")
    git(repository, "-c", "user.name=Build regression", "-c", "user.email=build@example.invalid",
        "commit", "-m", "fixture binary")
    sha = git(repository, "rev-parse", "HEAD")
    original = repository
    repository = repository.parent / "crlf-checkout"
    git(original, "-c", "core.autocrlf=true", "clone", "--no-hardlinks", str(original), str(repository))
    git(repository, "config", "core.autocrlf", "true")
    text = repository / "bossman_shared/runtime.py"
    assert b"\r\n" in text.read_bytes(), "negative control did not convert checkout bytes"
    assert git(repository, "status", "--porcelain") == ""
    assert identity.source_identity(repository)["source_dirty"] is True
    monkeypatch.setattr(builder, "ROOT", repository)
    with builder.clean_source_snapshot(sha) as snapshot:
        assert (snapshot / "bossman_shared/runtime.py").read_bytes() == b"VALUE = 1\n"
        assert (snapshot / "asset.bin").read_bytes() == binary
        assert identity.source_identity(snapshot) == {"source_sha": sha, "source_dirty": False}


@pytest.mark.parametrize("dirty", [True, None, "false", 1, 0, "missing"])
def test_installed_verifier_refuses_dirty_or_unmeasured_identity(tmp_path, dirty):
    path = tmp_path / "_build.json"
    value = {"source_sha": "a" * 40}
    if dirty != "missing":
        value["source_dirty"] = dirty
    path.write_text(json.dumps(value))
    with pytest.raises(AssertionError, match="dirty or unmeasured"):
        verifier.verified_source(path, "a" * 40)


def test_installed_verifier_accepts_only_clean_matching_sha(tmp_path):
    path = tmp_path / "_build.json"
    path.write_text(json.dumps({"source_sha": "a" * 40, "source_dirty": False}))
    assert verifier.verified_source(path, "a" * 40) == "a" * 40
    with pytest.raises(AssertionError):
        verifier.verified_source(path, "b" * 40)


def test_dirty_diagnostic_bundle_cannot_publish_verified_acceptance(tmp_path, monkeypatch):
    output = tmp_path / "diagnostic"
    monkeypatch.setattr(builder, "_source_sha", lambda: "a" * 40)
    monkeypatch.setattr(builder, "_source_dirty", lambda: True)
    monkeypatch.setattr(builder, "build_wheels", lambda *_: [])
    def no_verification(*_):
        pytest.fail("dirty source must never run exact-SHA verification")
    monkeypatch.setattr(builder, "verify", no_verification)
    monkeypatch.setattr(sys, "argv", ["build_local_bundle", "--out", str(output), "--allow-dirty"])
    assert builder.main() == 0
    manifest = json.loads((output / "MANIFEST.json").read_text())
    assert manifest["source_dirty"] is True
    assert manifest["checks"]["status"] == "DIRTY_SOURCE_NOT_VERIFIED"
