// Real Chromium + authenticated disposable BCC + actual media. No API mocks.
const { chromium } = require('playwright');
const fs = require('node:fs');
const assert = require('node:assert/strict');
(async () => {
  const base = process.env.VIDEO_UI_URL || 'http://127.0.0.1:8878';
  assert.equal(new URL(base).hostname, '127.0.0.1');
  for (const key of ['VIDEO_UI_TOKEN_FILE', 'VIDEO_UI_FIXTURE', 'VIDEO_UI_REPLACEMENT']) assert(process.env[key], key);
  const browser = await chromium.launch();
  try {
    const context = await browser.newContext({ viewport: { width: 1720, height: 1100 }, acceptDownloads: true });
    const page = await context.newPage(), errors = [], checks = [];
    page.on('pageerror', e => errors.push(e.message));
    const login = await context.request.post(base + '/api/login', { data: { token: fs.readFileSync(process.env.VIDEO_UI_TOKEN_FILE, 'utf8').trim() } });
    assert.equal(login.status(), 200); const auth = await login.json();
    await context.addInitScript(csrf => { localStorage.setItem('bcc.csrf', csrf); localStorage.setItem('vs.language', JSON.stringify('en')); }, auth.csrf);
    await page.goto(base + '/#/video-studio');
    await page.getByRole('button', { name: '＋ New project', exact: true }).click();
    await page.getByLabel('Name', { exact: true }).fill('Advanced UI verification');
    await page.getByRole('button', { name: 'Apply', exact: true }).click();
    await page.locator('.vs-library input[type=file]').setInputFiles(process.env.VIDEO_UI_FIXTURE);
    await page.locator('.vs-media-card').first().waitFor();
    await page.locator('.vs-media-card').first().dblclick();
    await page.locator('.vs-clip').first().waitFor();
    const id = new URLSearchParams(page.url().split('?')[1]).get('project_id');
    const snapshot = async () => (await context.request.get(`${base}/api/video-studio/projects/${id}`)).json();
    const command = async action => { const [response] = await Promise.all([page.waitForResponse(r => r.url().endsWith('/commands') && r.request().method() === 'POST'), action()]); assert.equal(response.status(), 200, await response.text()); return response.json(); };
    const number = async (label, value, owner = page) => command(async () => { const input = owner.getByLabel(label, { exact: true }); await input.fill(String(value)); await input.press('Tab'); });
    await page.locator('.vs-clip').first().click();
    await number('Source out, s', 1);
    const ruler = await page.locator('.vs-ruler').boundingBox();
    await page.mouse.click(ruler.x + 34, ruler.y + 8);
    await command(() => page.locator('.vs-studio').press('s'));
    let doc = await snapshot(); assert.equal(doc.sequences[0].tracks[0].clips.length, 2);
    assert.equal(doc.sequences[0].tracks[0].clips[1].start, 500000); checks.push('actual ruler playhead + keyboard split');
    await page.locator('.vs-clip').first().click(); await page.locator('.vs-clip').nth(1).click({ modifiers: ['Control'] });
    await command(() => page.getByRole('button', { name: 'Group', exact: true }).click());
    doc = await snapshot(); const clips = doc.sequences[0].tracks[0].clips; assert(clips[0].group_id); assert.equal(clips[0].group_id, clips[1].group_id); checks.push('Ctrl multiselect + durable grouping');
    await page.locator('.vs-clip').first().click();
    await page.getByRole('button', { name: 'Audio', exact: true }).click();
    await number('Volume', .7, page.locator('.vs-workspace-controls > label').first());
    doc = await snapshot(); assert.equal(doc.sequences[0].tracks[0].clips[0].volume, .7);
    await number('Pan', -.25, page.locator('.vs-mixer-strip').first());
    assert.equal((await snapshot()).sequences[0].tracks[0].pan, -.25); checks.push('clip gain + real track mixer pan');
    await page.getByRole('button', { name: '◇ Keyframe', exact: true }).click();
    await page.getByLabel('Parameter', { exact: true }).selectOption('volume');
    await page.getByLabel('Clip-local seconds', { exact: true }).fill('.25');
    await page.getByLabel('Value', { exact: true }).fill('.4');
    await page.getByLabel('Easing', { exact: true }).selectOption('ease_in_out');
    await command(() => page.locator('dialog').getByRole('button', { name: 'Apply', exact: true }).click());
    assert.deepEqual((await snapshot()).sequences[0].tracks[0].clips[0].keyframes.volume, [{ t: 250000, value: .4, easing: 'ease_in_out' }]); checks.push('timed audio automation + easing');
    await page.getByRole('button', { name: 'Captions', exact: true }).click();
    const [imported] = await Promise.all([page.waitForResponse(r => r.url().endsWith('/captions/import')), page.locator('dialog input[type=file]').setInputFiles({ name: 'captions.srt', mimeType: 'text/plain', buffer: Buffer.from('1\n00:00:00,000 --> 00:00:00,900\nЦена 1,234. Привет!\n') })]);
    assert.equal(imported.status(), 200, await imported.text());
    await page.getByLabel('Cue 1 text').fill('Цена 1,234. Редакция.');
    const [download] = await Promise.all([page.waitForEvent('download'), page.getByRole('button', { name: 'VTT ↓', exact: true }).click()]);
    const vtt = fs.readFileSync(await download.path(), 'utf8'); assert(vtt.includes('Цена 1,234. Редакция.')); assert(vtt.includes('00:00:00.900'));
    await command(() => page.locator('dialog').getByRole('button', { name: 'Apply', exact: true }).click());
    assert.equal((await snapshot()).captions[0].text, 'Цена 1,234. Редакция.'); checks.push('real SRT upload + timed caption edit + VTT text preservation');
    await page.locator('.vs-library input[type=file]').setInputFiles(process.env.VIDEO_UI_REPLACEMENT);
    await page.waitForFunction(() => document.querySelectorAll('.vs-media-card').length === 2);
    doc = await snapshot(); const original = doc.sequences[0].tracks[0].clips[0].media_id, replacement = Object.values(doc.media).find(m => m.id !== original);
    await page.locator('.vs-media-card').filter({ hasText: doc.media[original].name }).first().click();
    await page.getByRole('button', { name: 'Relink', exact: true }).click();
    await page.getByLabel('Imported replacement', { exact: true }).selectOption(replacement.id);
    const [relinked] = await Promise.all([page.waitForResponse(r => r.url().endsWith('/media/relink')), page.locator('dialog').getByRole('button', { name: 'Apply', exact: true }).click()]);
    assert.equal(relinked.status(), 200, await relinked.text());
    await page.waitForFunction(hash => [...document.querySelectorAll('.vs-thumb img')].every(img => img.src.includes(hash)), replacement.sha256);
    doc = await snapshot(); assert.equal(doc.media[original].sha256, replacement.sha256); assert.equal(doc.sequences[0].tracks[0].clips[0].media_id, original); checks.push('relink immutable reference preserving clip IDs');
    const waitJob = async accepted => {
      for (let i = 0; i < 120; i++) {
        const value = await (await context.request.get(`${base}/api/video-studio/exports/${accepted.job_id}`)).json();
        if (['completed', 'failed', 'stopped'].includes(value.status)) { assert.equal(value.status, 'completed', JSON.stringify(value)); return value; }
        await page.waitForTimeout(1000);
      }
      throw new Error('Job exceeded bounded test timeout');
    };
    const [preparing] = await Promise.all([page.waitForResponse(r => r.url().endsWith('/analysis')), page.getByRole('button', { name: 'Prepare proxy / waveform', exact: true }).click()]);
    assert.equal(preparing.status(), 200, await preparing.text()); await waitJob(await preparing.json());
    await page.waitForFunction(() => document.querySelector('.vs-source-waveform img')?.naturalWidth > 0);
    const wave = await context.request.get(`${base}/api/video-studio/media/${original}/waveform?project_id=${id}`); assert.equal(wave.status(), 200); assert.equal((await wave.body()).subarray(1, 4).toString(), 'PNG');
    await page.getByRole('button', { name: 'Proxy', exact: true }).click();
    await page.waitForFunction(() => document.querySelector('.vs-preview video')?.videoWidth === 640); checks.push('canonical cached preparation + actual waveform PNG and playable proxy');
    await page.locator('.vs-clip').first().click(); await page.getByRole('button', { name: 'Color', exact: true }).click();
    await page.getByRole('button', { name: 'Scopes · source snapshot', exact: true }).click();
    await page.getByLabel('Scope', { exact: true }).selectOption('histogram');
    const [scoped] = await Promise.all([page.waitForResponse(r => r.url().endsWith('/analysis')), page.locator('dialog').getByRole('button', { name: 'Apply', exact: true }).click()]);
    assert.equal(scoped.status(), 200, await scoped.text()); const scope = await waitJob(await scoped.json()); assert.equal(scope.analysis.snapshot, true); assert.equal(scope.analysis.live, false);
    await page.waitForFunction(() => document.querySelector('.vs-scope img')?.naturalWidth === 512); checks.push('actual timestamped scope snapshot, explicitly nonlive');
    await page.getByRole('button', { name: 'Export', exact: true }).click();
    await page.getByLabel('Profile', { exact: true }).selectOption('reels');
    assert.equal(await page.getByLabel('Width', { exact: true }).inputValue(), '');
    assert.equal(await page.getByLabel('Height', { exact: true }).inputValue(), '');
    const [exported] = await Promise.all([page.waitForResponse(r => r.url().endsWith('/exports') && r.request().method() === 'POST'), page.locator('dialog').getByRole('button', { name: 'Apply', exact: true }).click()]);
    const payload = exported.request().postDataJSON(); assert.equal('width' in payload.options, false); assert.equal(payload.options.profile, 'reels'); assert.equal(exported.status(), 200, await exported.text());
    const accepted = await exported.json(); let job;
    for (let i = 0; i < 120; i++) { await page.waitForTimeout(1000); job = await (await context.request.get(`${base}/api/video-studio/exports/${accepted.job_id}`)).json(); if (['completed', 'failed', 'stopped'].includes(job.status)) break; }
    assert.equal(job.status, 'completed', JSON.stringify(job)); assert.equal(job.verification?.passed, true); assert.equal(job.verification.width, 1080); assert.equal(job.verification.height, 1920); checks.push('actual Reels default dimensions + captions/audio/keyframes render and verify');
    await page.locator('.vs-header button[title=Project]').click();
    const [packaged] = await Promise.all([page.waitForResponse(r => r.url().endsWith('/portable')), page.getByRole('button', { name: 'Portable project', exact: true }).click()]);
    assert.equal(packaged.status(), 200, await packaged.text()); const portable = await waitJob(await packaged.json()); assert.equal(portable.verification.passed, true);
    const archive = await context.request.get(base + portable.output_url); assert.equal(archive.status(), 200); assert.equal((await archive.body()).subarray(0, 2).toString(), 'PK'); checks.push('actual portable ZIP job + verified source archive download');
    const packageBytes = await archive.body();
    await page.locator('.vs-header button[title=Project]').click(); await page.getByRole('button', { name: 'Import portable ZIP', exact: true }).click();
    const [restoring] = await Promise.all([page.waitForResponse(r => r.url().includes('/portable/import?')), page.getByLabel('Portable ZIP', { exact: true }).setInputFiles({ name: 'project.zip', mimeType: 'application/zip', buffer: packageBytes })]);
    assert.equal(restoring.status(), 200, await restoring.text()); const restored = await waitJob(await restoring.json()); assert.equal(restored.verification.passed, true);
    const restoredDoc = await snapshot(); assert.equal(Object.keys(restoredDoc.media).length, 2);
    await page.waitForFunction(revision => document.querySelector('.vs-footer')?.textContent.includes('r' + revision), restoredDoc.revision); checks.push('native portable ZIP restore with shared content IDs reverified');
    await page.locator('.vs-header button[title=Project]').click(); await page.getByRole('button', { name: 'OpenTimelineIO / Shotcut', exact: true }).click();
    const [otioDownload] = await Promise.all([page.waitForEvent('download'), page.getByRole('button', { name: 'OTIO ↓', exact: true }).click()]);
    const otio = fs.readFileSync(await otioDownload.path()); const parsed = JSON.parse(otio.toString()); assert(parsed.OTIO_SCHEMA);
    const [otioImported] = await Promise.all([page.waitForResponse(r => r.url().endsWith('/otio/import')), page.locator('dialog input[type=file]').setInputFiles({ name: 'roundtrip.otio', mimeType: 'application/json', buffer: otio })]);
    assert.equal(otioImported.status(), 200, await otioImported.text()); assert.equal((await snapshot()).sequences[0].tracks[0].clips.length, 2); checks.push('actual native OTIO export/import round trip');
    await page.screenshot({ path: '.audit-work/video-studio-advanced.png', fullPage: true });
    assert.deepEqual(errors, []); console.log(JSON.stringify({ project_id: id, revision: (await snapshot()).revision, checks, export_job: job, page_errors: errors }, null, 2));
  } finally { await browser.close(); }
})().catch(error => { console.error(error); process.exitCode = 1; });
