"""Regenerate ``command-center/bcc/telegram_calls/addon_lock.json`` (maintainers, networked machine; never by hand).

    python tools/telegram_calls_addon_lock.py [--python 3.12] [--platform win_amd64]

Resolves the exact wheel closure of the ``calls`` extra with pip's resolver for the TARGET platform (not the host), reads
the sha256 of every file from pip's report, and adds pure-Python sdists that have no wheel (pyaes) from the PyPI JSON API.
The Windows embedded runtime has no pip: ``bcc.telegram_calls.addon`` installs exactly these hash-verified files.
"""
from __future__ import annotations

import argparse
import json
import subprocess
import sys
import tempfile
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
LOCK = ROOT / "command-center" / "bcc" / "telegram_calls" / "addon_lock.json"
TOP = ["py-tgcalls==3.0.0", "ntgcalls==3.0.0", "pysilero-vad==3.4.0", "soxr==1.1.0", "telethon==1.45.0"]
CLOSURE = ["rsa", "pyasn1", "aiohttp", "deprecation", "yarl", "multidict", "frozenlist", "aiosignal", "aiohappyeyeballs",
           "propcache", "attrs", "idna", "packaging", "typing_extensions"]
PURE_SDISTS = {"pyaes": "package pyaes"}      # no wheel on PyPI; pure Python, extracted by the installer


def resolve(platform: str, python: str) -> list[dict]:
    with tempfile.TemporaryDirectory() as d:
        report = Path(d) / "report.json"
        subprocess.run([sys.executable, "-m", "pip", "install", "--dry-run", "--ignore-installed", "--quiet", "--report", str(report),
                        "--target", str(Path(d) / "t"), "--platform", platform, "--python-version", python, "--only-binary=:all:",
                        "--no-deps", *TOP, *CLOSURE], check=True)
        data = json.loads(report.read_text(encoding="utf-8"))
    out = []
    for item in data["install"]:
        meta, dl = item["metadata"], item["download_info"]
        out.append({"name": meta["name"], "version": meta["version"], "kind": "wheel", "filename": dl["url"].rsplit("/", 1)[-1],
                    "url": dl["url"], "sha256": dl["archive_info"]["hashes"]["sha256"]})
    return out


def pure_sdist(name: str) -> dict:
    with urllib.request.urlopen(f"https://pypi.org/pypi/{name}/json", timeout=30) as r:  # noqa: S310 - fixed https PyPI host
        info = json.load(r)
    version = info["info"]["version"]
    sdist = next(u for u in info["releases"][version] if u["packagetype"] == "sdist")
    return {"name": name, "version": version, "kind": "sdist_pure", "filename": sdist["filename"], "url": sdist["url"],
            "sha256": sdist["digests"]["sha256"], "package_dir": name, "size": sdist["size"]}


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--python", default="3.12")
    ap.add_argument("--platform", default="win_amd64")
    args = ap.parse_args()
    entries = resolve(args.platform, args.python) + [pure_sdist(n) for n in PURE_SDISTS]
    entries.sort(key=lambda e: e["name"].lower())
    lock = {"schema": 1, "target": f"{args.platform}-cp{args.python.replace('.', '')}",
            "note": "Generated by tools/telegram_calls_addon_lock.py; never edit by hand.", "packages": entries}
    LOCK.write_text(json.dumps(lock, indent=2) + "\n", encoding="utf-8")
    print(f"wrote {LOCK} ({len(entries)} packages)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
